spring.application.name=jspring-course
spring.datasource.url=jdbc:postgresql://localhost:5432/jspring
spring.datasource.username=jspring
spring.datasource.password=jspring
spring.jpa.hibernate.ddl-auto=update
